from pydantic import BaseModel, Field
from typing import Literal


class AgentSchema(BaseModel):
    messages: list = Field(description="Conversation messages recorded by the agent.")
    user_question: str = Field(description="Input from the user.")
    curated_ques: str = Field(description="Curated user question")
    prompt_query_context: str = Field(description="A detailed prompt with SQL DB context will help agent to generate sql query to fetch the data asked by user")
    generated_sql_query: str = Field(description="Generated SQL query by the agent")
    is_safe: float = Field(description="Indicates whether the generated sql query by the agent is safe to run or not")
    comments: str = Field(description="Comments on the generated sql query")
    is_correct_query: Literal["Yes", "No"] = Field(description="Indicates whether the generated sql query by the agent is correct for the user question or not")
    query_execution_result: str = Field(description="The result of the generated sql query")
    final_answer: str = Field(description="the Final answer generated by the agent")
    retry_count: int = Field(description="Counter to keep track of the number of retries for generating a correct SQL query. This is used to prevent infinite loops in case the agent fails to generate a correct query after multiple attempts.")